/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Echo API
 * Auto-generated API documentation for the Echo server
 * OpenAPI spec version: 1.0.0
 */
import type { LogCategory } from './logCategory.js'

export type GetLogsParams = {
  fromDate: string
  logCategories?: LogCategory | LogCategory[]
  logSearch?: string
}
